"model":
  "type": "DFNet"
  "params":
    "in_channels": 4
    "hidden_channels": 64
    "L": 5
    "k": 12

"inference":
  "checkpoint_path": "checkpoint/checkpoint.tar"
  "image_size": !!python/tuple [320, 240]
  "cuda_id": 0
  "depth_min": 0.4  # default 0.3 
  "depth_max": 0.7  # default 1.0
  "depth_norm": 1.0
